/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_yuvViewer_gui_YUVViewer */

#ifndef _Included_org_yuvViewer_gui_YUVViewer
#define _Included_org_yuvViewer_gui_YUVViewer
#ifdef __cplusplus
extern "C" {
#endif
#undef org_yuvViewer_gui_YUVViewer_FOCUS_TRAVERSABLE_UNKNOWN
#define org_yuvViewer_gui_YUVViewer_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef org_yuvViewer_gui_YUVViewer_FOCUS_TRAVERSABLE_DEFAULT
#define org_yuvViewer_gui_YUVViewer_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef org_yuvViewer_gui_YUVViewer_FOCUS_TRAVERSABLE_SET
#define org_yuvViewer_gui_YUVViewer_FOCUS_TRAVERSABLE_SET 2L
#undef org_yuvViewer_gui_YUVViewer_TOP_ALIGNMENT
#define org_yuvViewer_gui_YUVViewer_TOP_ALIGNMENT 0.0f
#undef org_yuvViewer_gui_YUVViewer_CENTER_ALIGNMENT
#define org_yuvViewer_gui_YUVViewer_CENTER_ALIGNMENT 0.5f
#undef org_yuvViewer_gui_YUVViewer_BOTTOM_ALIGNMENT
#define org_yuvViewer_gui_YUVViewer_BOTTOM_ALIGNMENT 1.0f
#undef org_yuvViewer_gui_YUVViewer_LEFT_ALIGNMENT
#define org_yuvViewer_gui_YUVViewer_LEFT_ALIGNMENT 0.0f
#undef org_yuvViewer_gui_YUVViewer_RIGHT_ALIGNMENT
#define org_yuvViewer_gui_YUVViewer_RIGHT_ALIGNMENT 1.0f
#undef org_yuvViewer_gui_YUVViewer_serialVersionUID
#define org_yuvViewer_gui_YUVViewer_serialVersionUID -7644114512714619750LL
#undef org_yuvViewer_gui_YUVViewer_serialVersionUID
#define org_yuvViewer_gui_YUVViewer_serialVersionUID 4613797578919906343LL
#undef org_yuvViewer_gui_YUVViewer_INCLUDE_SELF
#define org_yuvViewer_gui_YUVViewer_INCLUDE_SELF 1L
#undef org_yuvViewer_gui_YUVViewer_SEARCH_HEAVYWEIGHTS
#define org_yuvViewer_gui_YUVViewer_SEARCH_HEAVYWEIGHTS 1L
#undef org_yuvViewer_gui_YUVViewer_OPENED
#define org_yuvViewer_gui_YUVViewer_OPENED 1L
#undef org_yuvViewer_gui_YUVViewer_serialVersionUID
#define org_yuvViewer_gui_YUVViewer_serialVersionUID 4497834738069338734LL
/*
 * Class:     org_yuvViewer_gui_YUVViewer
 * Method:    calculateFastRGBImage
 * Signature: (ZZZII[B[B[B[I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_yuvViewer_gui_YUVViewer_calculateFastRGBImage
  (JNIEnv *, jclass, jboolean, jboolean, jboolean, jint, jint, jbyteArray, jbyteArray, jbyteArray, jintArray);

/*
 * Class:     org_yuvViewer_gui_YUVViewer
 * Method:    calculateFastColoredRGBImage
 * Signature: (II[B[B[B[I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_yuvViewer_gui_YUVViewer_calculateFastColoredRGBImage
  (JNIEnv *, jclass, jint, jint, jbyteArray, jbyteArray, jbyteArray, jintArray);

/*
 * Class:     org_yuvViewer_gui_YUVViewer
 * Method:    calculateRGBImage
 * Signature: (ZZZII[B[B[B[I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_yuvViewer_gui_YUVViewer_calculateRGBImage
  (JNIEnv *, jclass, jboolean, jboolean, jboolean, jint, jint, jbyteArray, jbyteArray, jbyteArray, jintArray);

/*
 * Class:     org_yuvViewer_gui_YUVViewer
 * Method:    resizeRGBImage
 * Signature: (III[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_yuvViewer_gui_YUVViewer_resizeRGBImage
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
