/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_yuvViewer_gui_YUVViewer_Play */

#ifndef _Included_org_yuvViewer_gui_YUVViewer_Play
#define _Included_org_yuvViewer_gui_YUVViewer_Play
#ifdef __cplusplus
extern "C" {
#endif
#undef org_yuvViewer_gui_YUVViewer_Play_MIN_PRIORITY
#define org_yuvViewer_gui_YUVViewer_Play_MIN_PRIORITY 1L
#undef org_yuvViewer_gui_YUVViewer_Play_NORM_PRIORITY
#define org_yuvViewer_gui_YUVViewer_Play_NORM_PRIORITY 5L
#undef org_yuvViewer_gui_YUVViewer_Play_MAX_PRIORITY
#define org_yuvViewer_gui_YUVViewer_Play_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
