#!/bin/bash
if type ant > /dev/null
then
	ant
else
	echo 'Installing Apache Ant is not installed'
	echo 'Make shure ant exists is in your path and is executable'
	echo 'Installing Apache Ant http://ant.apache.org/manual/install.html'
fi
#cd gui
#javap -s -p YUVViewer
cd ~/IdeaProjects/yuvviewer/
if type javah > /dev/null
then
	javac -h src/org/yuvViewer/gui/ src/org/yuvViewer/gui/FrameAboutBox.java \
	src/org/yuvViewer/gui/MainFrame.java \
	src/org/yuvViewer/gui/SettingsDialog.java \
	src/org/yuvViewer/gui/YUVViewer.java \
	src/org/yuvViewer/utils/YUVDeclaration.java \
	src/org/yuvViewer/utils/ExtensionFileFilter.java \
	src/org/yuvViewer/utils/ExtensionUtils.java  \
	src/org/yuvViewer/utils/WholeNumberTextField.java
else
	echo 'javah is not installed'
fi
	cd ~/IdeaProjects/yuvviewer/src/org/yuvViewer/gui/
if type gcc > /dev/null
then
	gcc -shared -I/usr/lib/jvm/java-14-openjdk-amd64/include/linux/ -I/usr/lib/jvm/java-14-openjdk-amd64/include/ YUVViewerImplementation.c -o libcalc.so
	sudo cp libcalc.so /usr/local/lib/
else
	echo 'gcc is not installed'
fi
if type java > /dev/null
then
	java -cp ~/IdeaProjects/yuvviewer/src/:. org.yuvViewer.Main
else
	echo 'java is not installed'
fi
