#!/bin/bash
CWD="${PWD}"
JVM="/usr/lib/jvm/"
JDK="java-14-openjdk-amd64"
GUI="src/org/yuvViewer/gui/"
UTILS="src/org/yuvViewer/utils/"
INCLUDE="/include/"
LINUX="linux/"
if type ant > /dev/null
then
	ant
else
	echo 'Apache Ant is not installed. Make shure ant exists is in your path and is executable'
	echo 'Installing Apache Ant http://ant.apache.org/manual/install.html'
fi
#javap -s -p YUVViewer
if type javah > /dev/null
then
	javac -h "${GUI}" "${GUI}FrameAboutBox.java" \
	"${GUI}MainFrame.java" \
	"${GUI}SettingsDialog.java" \
	"${GUI}YUVViewer.java" \
	"${UTILS}YUVDeclaration.java" \
	"${UTILS}ExtensionFileFilter.java" \
	"${UTILS}ExtensionUtils.java"  \
	"${UTILS}WholeNumberTextField.java"
else
	echo 'javah is not installed'
fi
	cd "${GUI}"
if type gcc > /dev/null
then
	gcc -shared -I"${JVM}${JDK}${INCLUDE}${LINUX}" -I"${JVM}${JDK}${INCLUDE}" YUVViewerImplementation.c -o libcalc.so
	sudo mv libcalc.so /usr/local/lib/
else
	echo 'gcc is not installed'
fi
if type java > /dev/null
then
	java -cp "${CWD}/src/:." org.yuvViewer.Main
else
	echo 'java is not installed'
fi
